CREATE SCHEMA IF NOT EXISTS secureCapita;

SET NAMES 'UTF8MB4';
SET TIME_ZONE = 'US/Eastern';

USE secureCapita;

DROP TABLE IF EXISTS Users;

CREATE TABLE Users
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) DEFAULT NOT NULL,
    address VARCHAR(255) DEFAULT NOT NULL,
    phone

);